version: '3.7'

services:

  web-prod:
    container_name: web-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
      
volumes: 
  node_modules:
  data:
    