version: '3.7'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes: 
  node_modules:
  data:
    